services:
  - type: web
    name: my-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    branch: main
    autoDeploy: true
